# Activation Functions

## ReLU Activation Function Code

In [97]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]

output = []
for i in inputs:
    if i > 0:
        output.append(i)
    else:
        output.append(0)

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [98]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]

output = []
for i in inputs:
    output.append(max(0, i))

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [99]:
import numpy as np

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [100]:
import matplotlib.pyplot as plt
from nnfs.datasets import spiral_data

In [101]:
class Layer_Dense:

    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    # Forward Pass
    def forward(self, inputs):
        # Calculate output values from inputs, wights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

In [102]:
class Activation_ReLU:
    
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from input
        self.output = np.maximum(0, inputs)

In [103]:
# Create dataset
X,y = spiral_data(samples = 100, classes = 3)

# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Forward pass through activation func.
# Takes in output from previous layer
activation1.forward(dense1.output)

In [104]:
print(activation1.output[:5])

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.15718497e-04 0.00000000e+00 5.70168935e-05]
 [1.22796493e-04 0.00000000e+00 1.07157016e-04]
 [2.02090049e-04 0.00000000e+00 1.65252211e-04]
 [2.96694498e-04 0.00000000e+00 2.26509192e-04]]


### The Softmax Activation Function

In [105]:
# Values from the previous output when we described
# what a nerual network is
layer_outputs = [4.8, 1.21, 2.385]

# e - mathematical constant, we use for E here to match a common coding
# style where constants are uppercased
E = 2.71828182846 # you can also use math.e

# For each value in a vector, calculate the exponential value
exp_values = []
for output in layer_outputs:
    exp_values.append(E ** output)
print('exponentiated values:')
print(exp_values)

exponentiated values:
[121.51041751893969, 3.3534846525504487, 10.85906266492961]


In [106]:
# Now normalize values
norm_base = sum(exp_values) # We sum all values
norm_values = []
for value in exp_values:
    norm_values.append(value / norm_base)
print("Normalized exponentiated values:")
print(norm_values)

print("Sum of normalized values:", sum(norm_values))

Normalized exponentiated values:
[0.8952826639573506, 0.024708306782070668, 0.08000902926057876]
Sum of normalized values: 1.0


In [107]:
import numpy as np

# Values from the earlier previous when we described
# what a neural network is
layer_outputs = [ 4.8 , 1.21 , 2.385 ]

# For each value in a vector, calculate the exponential value
exp_values = np.exp(layer_outputs)
print('exponentiated values:')
print(exp_values)

# Now normalize values
norm_values = exp_values / np.sum(exp_values)
print("normalized exponentiated values:")
print(norm_values)

print("sum of normalized values:", sum(norm_values))

exponentiated values:
[121.51041752   3.35348465  10.85906266]
normalized exponentiated values:
[0.89528266 0.02470831 0.08000903]
sum of normalized values: 0.9999999999999999


In [108]:
# get unnormalized probabilities
exp_values = np.exp([inputs])

# Normalize them for each sample
probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

In [109]:
import numpy as np

layer_outputs = np.array([[4.8, 1.21, 2.385],
                            [8.9, -1.81, 0.2],
                            [1.41, 1.051, 0.026]])

print("Sum without axis")
print(np.sum(layer_outputs))

print("This will be identical to the above since default is None:")
print(np.sum(layer_outputs, axis=None))

Sum without axis
18.172
This will be identical to the above since default is None:
18.172


In [110]:
print('Another way to think of it w/ a matrix == axis 0: columns:')
print(np.sum(layer_outputs, axis = 0))

Another way to think of it w/ a matrix == axis 0: columns:
[15.11   0.451  2.611]


In [111]:
print('But we want to sum the rows instead, like this w/ raw py:')
for i in layer_outputs:
    print(sum(i))

But we want to sum the rows instead, like this w/ raw py:
8.395
7.29
2.4869999999999997


In [112]:
print('So we can sum axis 1, but note the current shape:')
print(np.sum(layer_outputs, axis=1))

So we can sum axis 1, but note the current shape:
[8.395 7.29  2.487]


In [113]:
print("Sum axis 1, but keep the same dimensions as input:")
print(np.sum(layer_outputs, axis=1, keepdims=True))

Sum axis 1, but keep the same dimensions as input:
[[8.395]
 [7.29 ]
 [2.487]]


In [114]:
class Activation_Softmax:
    
    # Forward pass
    def forward(self, inputs):
        
        # Get unnormalized probabilites
        exp_values = np.exp(inputs - np.max(inputs, axis=1,
                                                keepdims=True))
        
        # Normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1,
                                                keepdims=True)
        self.output = probabilities

In [115]:
# Create dataset

X,y = spiral_data(samples=100, classes=3)

# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Create ReLU activation (to be used with Dense layer)
activation1 = Activation_ReLU()

# Create second Dense layer with 3 input features (as we take output
# of previous layer here) and 3 output values
dense2 = Layer_Dense(3,3)

# Create Softmax activation (to be used with Dense layer):
activation2 = Activation_Softmax()

# Make a forward pass of our training data through this layer
dense1.forward(X)

# Make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)

# Make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)

# Make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)

# Let's see output of the first few samples:
print (activation2.output[: 5 ])

[[0.33333333 0.33333333 0.33333333]
 [0.33333351 0.33333293 0.33333356]
 [0.33333361 0.33333274 0.33333365]
 [0.33333368 0.33333259 0.33333373]
 [0.33333387 0.33333217 0.33333396]]
